language: php

branches:
  only:
    - master
    - development

php:
  - 5.5
  - 5.4

before_script:
  - php -r "eval('?>'.file_get_contents('https://getcomposer.org/installer'));"
  - php composer.phar update --prefer-source

script: vendor/bin/phpunit --coverage-text

notifications:
  email:
    - mudi@renegare.com